### ISSUE TITLE
Could not start CoverageCalculator from applauncher

### ISSUE THREAD

**Issue by NicoNeureiter** [rbouckaert/Experimenter#1]
Starting CoverageCalculator from applauncher raised the following error:
java.lang.ClassNotFoundException: beast.experimente.CoverageCalculator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at beast.util.BEASTClassLoader.forName(Unknown Source)
	at beast.app.tools.AppLauncher.runAppFromCMD(Unknown Source)
	at beast.app.tools.AppLauncher$PackageAppThread.run(Unknown Source)

Replacing "beast.experimente." by "beast.experimenter." in version.xml fixed the issue for me.

**Comment by rbouckaert** [comment]
Thanks for pointing this out!. Be aware that this package is merged with [beast-validation](https://github.com/christiaanjs/beast-validation) now (which suffered from the same problem),  and beast-validation is maintained, while this package is no longer maintained.
